export const COMMON_GRAPES = [
  "Cabernet Sauvignon",
  "Merlot",
  "Pinot Noir",
  "Syrah / Shiraz",
  "Grenache / Garnacha",
  "Malbec",
  "Tempranillo",
  "Sangiovese",
  "Nebbiolo",
  "Zinfandel / Primitivo",
  "Barbera",
  "Cabernet Franc",
  "Carignan",
  "Cinsault",
  "Mourvèdre / Monastrell",
  "Petit Verdot",
  "Pinot Meunier",
  "Touriga Nacional",
  "Gamay",
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio / Pinot Gris",
  "Chenin Blanc",
  "Viognier",
  "Sémillon",
  "Muscat / Moscato",
  "Albariño",
  "Gewürztraminer",
  "Grüner Veltliner",
  "Vermentino",
  "Garnacha Blanca",
  "Roussanne",
  "Marsanne",
  "Torrontés",
] as const

export type CommonGrape = (typeof COMMON_GRAPES)[number]
